resources:
- name: task-app-repo
  type: git
  icon: github
  source:
    branch: TA-09-CONCOURSE-CI-TEST
    uri: https://github.com/devankur03/task-app.git 

- name: node-image
  type: registry-image
  source:
    repository: node
    tag: 18

jobs:
- name: e2e-test-deployment-((stage))
  public: true
  plan:
  - get: node-image
  - get: task-app-repo
    trigger: true
  - task: install
    image: node-image
    config:
      inputs:
      - name: task-app-repo
      outputs:
      - name: dependencies
        path: task-app-repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["install"]
        dir: task-app-repo
  # - task: test
  #   image: node-image
  #   config:
  #     inputs:
  #     - name: task-app-repo
  #     - name: dependencies
  #       path: task-app-repo/node_modules
  #     platform: linux
  #     run:
  #       path: npm
  #       args: ["run", "test"]
  #       dir: task-app-repo
  - task: build
    image: node-image
    config:
      inputs:
      - name: task-app-repo
      - name: dependencies
        path: task-app-repo/node_modules
      outputs:
      - name: task-app-repo
        #path: task-app-repo/dist
      platform: linux
      
      # run:
      #   path: npm
      #   args: ["run", " build", " &&", " ls"]
      #   dir: task-app-repo
      run:
          path: /bin/sh
          args:
            - -cx
            - |
              ls -l
              cd task-app-repo
              npm run build
              ls 
              ls dist


  - task: verify-deploy-app
    # input_mapping:
    #    repository: task-app-repo
    config:
      inputs:
      - name: task-app-repo
      - name: dependencies
        path: task-app-repo/node_modules
      platform: linux
      image_resource:
        type: docker-image
        source:
          email: ((docker-hub-email))
          username: ((docker-hub-username))
          password: ((docker-hub-password))
          repository: ((docker-hub-username))/aws-container
      run:
        path: /bin/sh
        args: ['task-app-repo/concourse/task.sh','task-av03-web',"Repo-name-taskapp",((access_key)),((secret_key)),"hello"]
      # run:
      #     path: /bin/sh
      #     args:
      #       - -cx
      #       - |
      #         pwd
      #         aws --version
      #         ls
      #         ls task-app-repo
      #         mkdir test-result
      #          ls task-app-repo
      #         ./task-app-repo/concourse/task.sh
             


             

  # - task: deploy
  
  #   # config:
  #   #   inputs:
  #   #   - name: task-app-repo
  #   # input_mapping:
  #   #    repository: task-app-repo
     
  #   file: task-app-repo/concourse/task.yml
  #   params:
  #    S3_BUCKET: task-av03-web
  #    DESTINATION_FOLDER: /
  #    SOURCE_FOLDER: task-app-repo
            
